- experiment_name: overfit
  type: overfit
  dataset.folder: ./data/sdf/single/train/1a9b552befd6306cc8f2d5fe7449af61.obj.npy
  dataset.supervision: sdf
  arch.modulated_layer_idxs: [[1,3], [2,4]]

- experiment_name: meta_on_one_shape
  type: generalize
  dataset.folder: ./data/sdf/single
  dataset.supervision: sdf
  arch.modulated_layer_idxs: [[0], [1], [2], [3], [4], [5], [1,3], [2,4], [1,2], [3,4]]

