type: generalize
trainer: stage_inr
dataset:
  type: shapenet
  supervision: sdf
  folder: ./data/sdf/single
  transforms:
    type: shapenet
arch:
  type: meta_low_rank_modulated_inr
  ema: null
  rank:
  - 128
  modulated_layer_idxs:
  - 1
  - 3
  use_factorization: false
  n_inner_step: 4
  inner_lr: 0.003
  coord_sampler:
    data_type: image
    coord_range:
    - -1.0
    - 1.0
    train_strategy: null
    val_strategy: null
  hyponet:
    type: mlp
    n_layer: 6
    hidden_dim:
    - 256
    use_bias: true
    input_dim: 3
    output_dim: 2
    output_bias: 0.5
    fourier_mapping:
      type: PE
      trainable: false
      use_ff: true
      ff_sigma: 0
      ff_dim: 3
    activation:
      type: relu
      siren_w0: null
    initialization:
      weight_init_type: kaiming_uniform
      bias_init_type: zero
    normalize_weight: true
loss:
  type: mse
  subsample:
    type: null
    ratio: 0.1
  coord_noise: null
optimizer:
  type: adam
  init_lr: 0.0001
  weight_decay: 0.0001
  betas:
  - 0.9
  - 0.95
  warmup:
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.001
    mode: adaptive
    step_size: 1000
    gamma: 0.8
    patience: 30
    patience_adaptive: 6
    factor: 0.8
    threshold: 0
    start_from_zero: true
  max_gn: null
experiment:
  amp: true
  batch_size: 2
  total_batch_size: 2
  epochs: 10000
  epochs_cos: 30
  save_ckpt_freq: 20
  test_freq: 1
  test_imlog_freq: 200
